# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tutoriales Hackro
email: hackro91@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Mobile Developer
baseurl: "http://david-hackro.github.io/Curso-Android" # the subpath of your site, e.g. /blog
url: "http://david-hackro.github.io/Curso-Android/" # the base hostname & protocol for your site

# Social media profiles - feel free to add more here
twitter_username: DavidHackro
github_username:  david-hackro
facebook_username: TutorialesHackro
stackoverflow_username: david-hackro
linkedin_username: davidhackro



# Address information
address_street: 
address_city: Puebla
address_state: MX
address_zip: 

# Build settings
markdown: kramdown
